### ISSUE TITLE
ImportError: cannot import name poll

### ISSUE THREAD

**Issue by AbdullahAlshraa** [OpenState-SDN/ryu#13]
Hi everyone,

I am trying to launch https://github.com/OpenState-SDN/spider

when I try to Launch SPIDER:
$ cd ~/spider/src
$ sudo ryu-manager SPIDER_ctrl_WEBAPP.py

I get

Traceback (most recent call last):
File "/usr/local/bin/ryu-manager", line 9, in 
load_entry_point('ryu==3.29', 'console_scripts', 'ryu-manager')()
File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 88, in main
app_mgr.load_apps(app_lists)
File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 401, in load_apps
cls = self.load_app(app_cls_name)
File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 378, in load_app
mod = utils.import_module(name)
File "/usr/local/lib/python2.7/dist-packages/ryu/utils.py", line 91, in import_module
import(name)
File "/home/mininet/spider/src/SPIDER_ctrl_WEBAPP.py", line 25, in 
import SPIDER_ctrl
File "/home/mininet/spider/src/SPIDER_ctrl.py", line 30, in 
import SPIDER_parser
File "/home/mininet/spider/src/SPIDER_parser.py", line 33, in 
from mininet.topo import Topo
File "build/bdist.linux-x86_64/egg/mininet/topo.py", line 14, in 
File "build/bdist.linux-x86_64/egg/mininet/util.py", line 7, in 
ImportError: cannot import name poll

Plesae, how to handle with this situation
thanks in advance

**Comment by AbdullahAlshraa** [comment]
Whatever, I think my problem it is in this lines:

from mininet.topo import Topo
File "build/bdist.linux-x86_64/egg/mininet/topo.py", line 14, in 
File "build/bdist.linux-x86_64/egg/mininet/util.py", line 7, in
ImportError: cannot import name poll

when I use SSh to get in (build/bdist.linux-x86_64), I didn't find anything inside.
So I think I must firstly add the missing files then I could solve my solution.

I do not know how I can do that
please, If you have any advice, it would be appreciated 

I look forward to hearing you

**Comment by ccascone** [comment]
Hi @AbdullahAlshraa,

What is your environment? OS version? Mininet version?
Are you working on a VM configured as specified here? http://openstate-sdn.org/

Thanks,
Carmelo

**Comment by AbdullahAlshraa** [comment]
Dear Carmelo,

First of all, I would like to thank you for your consideration.
It might bothers you, but let me explain the environment that I use then what I guess it is my problem.

I use windows 10  + virtualbox.
>>>
I do the first step using ssh

I use the next command to install OpenState-enabled softswitch and controller in only one shot!
bash -c "$(wget -O - http://openstate-sdn.org/install.sh)"

then
I configure virtual box as follow:
I select Linux type, version Ubuntu 64
I do the first step 
then I set the first adaptor (NAT)>> click advance then forwarding port << add new rule( 8080 for host port, 8080 for local host port)

I set the  second adaptor (host- only Ethernet adapter\promiscuous mode: Allow All )
>>>
I tried mininet versions of 2.2.1 (32 bit), 2.2.1 (64 bit), 2.2.2 (64 bit), 2.2.2 (32 bit) and 2.2.0
>>>
>>
and I also tried to install them separately form their Repositories :

OpenState softswitch https://github.com/OpenState-SDN/ofsoftswitch13

OpenState controller https://github.com/OpenState-SDN/ryu
>>>>>

Whatever, I think my problem it is in this lines:

from mininet.topo import Topo
File "build/bdist.linux-x86_64/egg/mininet/topo.py", line 14, in File "build/bdist.linux-x86_64/egg/mininet/util.py", line 7, in
ImportError: cannot import name poll

when I use SSh to get in (build/bdist.linux-x86_64), I didn't find anything inside.
So I think I must firstly add the missing files then I could solve my solution.

I do not know how I can do that
please, If you have any advice, it would be appreciated 

I look forward to hearing you

**Comment by AbdullahAlshraa** [comment]
Dear Carmelo,

First of all, I would like to thank you for your consideration.
It might bothers you, but let me explain the environment that I use then what I guess it is my problem.

I use windows 10 (64-bit) + virtualbox.

I select Linux type, version Ubuntu 64, Memory size 2048 MB and using Mininet 2.2.1.

(1) I do the first step using Mininet Shell where I type the next command to install OpenState-enabled softswitch and controller in only one shot!

$ bash -c "$(wget -O - http://openstate-sdn.org/install.sh)"

(2) Thereafter, I access to etc/ssh/sshd_config to modfiy the listening port from 22 to 8080.

I configure virtual box as follow:
I set the first adaptor
 (NAT)>> click advance then forwarding port << add new rule( 8080 for the host port of (127.0.0.1), 8080 for local host portof (10.0.2.15))

(3)I type, in the command prompot, " putty.exe mininet@127.0.0.1 -P 8080 "

(4)Inside mininet Shell, I type $git clone http://github.com/OpenState-SDN/spider

(5)Launch SPIDER:(inside Mininet Shell ) -and I also tried in the terminal-
I type $ cd ~/spider/src $ sudo ryu-manager SPIDER_ctrl_WEBAPP.py

then, I get the aforementioned error
--------------------------------------------------------------------------------------------

in the Step one I tried to check out the some OpenState sample applications 
(https://github.com/OpenState-SDN/ryu/wiki)
when I check out the fualt management (https://github.com/OpenState-SDN/ryu/wiki/Failure-Recovery), I get the same error after I run these commands

cd ~/ryu/ryu/app/openstate/fail_recovery
sudo ryu-manager fault_tolerance_rest_ff_demo_probing.py
____________________________________________________________________________________________________


I tried mininet versions of 2.2.1 (32 bit), 2.2.1 (64 bit), 2.2.2 (64 bit), 2.2.2 (32 bit) and 2.2.0

and I also tried to install the (OpenState-enabled softswitch and controller) separately from their Repositories :

OpenState softswitch https://github.com/OpenState-SDN/ofsoftswitch13

OpenState controller https://github.com/OpenState-SDN/ryu
______________________________________________________________________________________________________

Whatever, I think my problem it is either in these lines:


File "build/bdist.linux-x86_64/egg/mininet/topo.py", line 14,in
File "build/bdist.linux-x86_64/egg/mininet/util.py", line 7, in
ImportError: cannot import name poll

when I use SSh to get in (build/bdist.linux-x86_64), I didn't find anything inside.
So I guess, I must firstly add the missing files then I could solve my problem.

Or, there is perhaps no compatibility between the SPIDER code and the packages that I download from http://openstate-sdn.org ( OpenState-enabled softswitch and controller)

please, If you have any advice, it would be appreciated

I look forward to hearing you
